### 1. StoreId로 전체 ReviewList 조회
GET http://localhost:8080/api/v1/review?storeId=5ca2a451-a578-11ef-a7cd-d8bbc1571db6

### 2. OrderId로 Review 조회
GET http://localhost:8080/api/v1/review/orderId?orderId=6a14f583-ed7b-4f97-970c-a8f105e084d5


### 3. 신규 Review 추가
POST http://localhost:8080/api/v1/review
Content-Type: application/json

{
  "memberId": "5c9de957-a578-11ef-a7cd-d8bbc1571db6",
  "orderId": "6a14f583-ed7b-4f97-970c-a8f105e084d5",
  "reviewContent": "단골인데 오늘은 별로 ㅠ",
  "reviewScore": 1
}

### 4. Review 삭제
PATCH http://localhost:8080/api/v1/review?reviewId=e6a48938-42f8-491d-8ffb-0b7f65f72e11&username=user1